### ISSUE TITLE
error: dsn.core.dll is missing from your computer.

### ISSUE THREAD

**Issue by silicaRich** [Microsoft/rDSN#200]
I followed these steps (on Windows 8.1 & VS 2015)
https://github.com/Microsoft/rDSN/wiki/Installation
and when I typed in this command  "run.cmd test Debug .\builddbg"
the following error came up:
![image](https://cloud.githubusercontent.com/assets/1787212/25503482/9dbd902e-2b68-11e7-9140-04e7e122a045.png)

I tried to google this, reclone the repo, rebuild, to no avail. wondering if you or anyone has encountered this issue before.

if it helps, my system variable is: 
![image](https://cloud.githubusercontent.com/assets/1787212/25503845/b9c560de-2b69-11e7-98f2-dee2c043dc12.png)

Thanks :)

**Comment by linmajia** [comment]
Sorry for late response. This is because the path of those built binaries is not set by the test script. Please execute the following command in c:\rDSN (suppose you are building 'Debug' version):
    SET Path=.\builddbg\bin\Debug;.\builddbg\lib;%Path%
    
Some tests require zookeeper, so you may need to install Java and run "run.cmd start_zk" before running the tests.

We are fixing this issue and the wiki.

**Comment by linmajia** [comment]
This issue is fixed in master branch.
