### ISSUE TITLE
What's the consensus protocol used in the replication?

### ISSUE THREAD

**Issue by lshmouse** [Microsoft/rDSN#8]
Very impressive project.

I have some questions and thanks for pointing out if I am wrong.

What's the consensus protocol used in the replication?
From the replication code, it seems to be the PacificA(http://research.microsoft.com/pubs/66814/tr-2008-25.pdf). Is this true?

As I known, the PacificA depends on a HA meta meta service to store the partition configuration. Is the current implements of meta service HA?

**Comment by imzhenyu** [comment]
Nice digging, Ishmouse. You are right that the current implementation is largely following PacificA, with minor changes though. We used to use a Microsoft internal Paxos library for production, but it is removed due to open source. Currently, the meta server supports durability, but not HA. We are evaluating ZooKeeper right now and will use it for HA of the meta server.  Let me know if you have more questions.

Thanks,
Zhenyu

**Comment by lshmouse** [comment]
Thanks for your response~
